import { DatabaseSchema } from './db.js';

export const initialSeedData: DatabaseSchema = {
  users: [
    {
      id: 'usr_demo_01',
      name: 'Aarav Sharma',
      email: 'user@medibasket.com',
      phone: '+91 98765 43210',
      role: 'user',
      address: 'Flat 402, Green Glen Residency, Outer Ring Road, Bellandur',
      city: 'Bengaluru',
      pincode: '560103',
      createdAt: '2026-08-10T10:00:00Z',
    },
    {
      id: 'usr_admin_01',
      name: 'Admin Officer',
      email: 'admin@medibasket.com',
      phone: '+91 91234 56789',
      role: 'admin',
      address: 'MediBasket Hub, Sector 4',
      city: 'Bengaluru',
      pincode: '560001',
      createdAt: '2026-08-01T09:00:00Z',
    },
  ],
  categories: [
    {
      id: 'first-aid',
      name: 'First Aid',
      icon: 'HeartPulse',
      description: 'Sterile dressings, antiseptic solutions, burn care, and wound treatment supplies',
    },
    {
      id: 'hygiene',
      name: 'Hygiene',
      icon: 'ShieldCheck',
      description: 'Sanitizers, antibacterial wipes, disinfectant sprays, and dental hygiene',
    },
    {
      id: 'personal-care',
      name: 'Personal Care',
      icon: 'Sparkles',
      description: 'Hydration salts, skin protectants, balm, and daily wellness essentials',
    },
    {
      id: 'emergency-essentials',
      name: 'Emergency Essentials',
      icon: 'Flame',
      description: 'Survival blankets, emergency whistle, high-lumen flashlights, multi-tools',
    },
    {
      id: 'travel-essentials',
      name: 'Travel Essentials',
      icon: 'Plane',
      description: 'Motion sickness bands, compact travel pouches, insect repellent, mini sanitizers',
    },
    {
      id: 'sports-care',
      name: 'Sports Care',
      icon: 'Activity',
      description: 'Instant cold packs, crepe bandages, muscle relief sprays, blister pads',
    },
    {
      id: 'college-essentials',
      name: 'College Essentials',
      icon: 'GraduationCap',
      description: 'Late-night study emergency kits, dorm first aid, rapid digital thermometer',
    },
    {
      id: 'home-essentials',
      name: 'Home Essentials',
      icon: 'Home',
      description: 'Family emergency first-aid box, burn shields, pulse oximeter, digital monitors',
    },
    {
      id: 'prescription-medicines',
      name: 'Prescription Medicines (Rx)',
      icon: 'Pill',
      description: 'Doctor-prescribed antibiotics, chronic care, and inhalers verified by licensed pharmacists',
    },
  ],
  products: [
    {
      id: 'prod_01',
      name: 'Sterile Waterproof Bandages (Pack of 50)',
      description: 'Flexible, breathable, waterproof adhesive dressings for cuts and minor abrasions. Hypoallergenic and non-stick pad.',
      category: 'First Aid',
      price: 149,
      originalPrice: 199,
      brand: 'MediGuard',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      stock: 45,
      rating: 4.8,
      reviewsCount: 128,
      specifications: {
        'Quantity': '50 strips in 3 sizes',
        'Material': 'Breathable PU Film',
        'Sterilization': 'Ethylene Oxide Gas',
        'Waterproof': 'Yes (up to 8 hours)',
      },
      usageInfo: 'Clean the wound area thoroughly with sterile water or antiseptic wipe before applying strip. Change bandage daily or when wet.',
      isEssential: true,
      createdAt: '2026-08-01T10:00:00Z',
    },
    {
      id: 'prod_02',
      name: 'Sterile Cotton Gauze Swabs (10x10 cm, 20 Pcs)',
      description: '100% pure cotton medical gauze swabs with folded edges to prevent fraying. Highly absorbent for wound dressing.',
      category: 'First Aid',
      price: 120,
      originalPrice: 160,
      brand: 'SurgiSafe',
      image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=600&q=80',
      stock: 32,
      rating: 4.7,
      reviewsCount: 84,
      specifications: {
        'Size': '10 cm x 10 cm (8 ply)',
        'Pieces': '20 sterile packets',
        'Absorption': 'Ultra-high fluid retention',
      },
      usageInfo: 'Open sterile envelope immediately before use. Apply over cleaned wound and secure with medical tape or roller bandage.',
      isEssential: true,
      createdAt: '2026-08-01T10:30:00Z',
    },
    {
      id: 'prod_03',
      name: 'Povidone Iodine Antiseptic Solution (100 ml)',
      description: 'Broad-spectrum non-prescription topical antiseptic solution for cleansing cuts, grazes, minor burns, and scrapes.',
      category: 'First Aid',
      price: 110,
      originalPrice: 135,
      brand: 'Betadine Care',
      image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80',
      stock: 28,
      rating: 4.9,
      reviewsCount: 215,
      specifications: {
        'Volume': '100 ml bottle with dropper',
        'Active Component': 'Povidone-Iodine 5% w/v',
        'Packaging': 'Child-resistant squeeze bottle',
      },
      usageInfo: 'Apply topically undiluted directly to affected area with sterile cotton gauze. Do not swallow or apply into deep puncture wounds.',
      isEssential: true,
      createdAt: '2026-08-01T11:00:00Z',
    },
    {
      id: 'prod_04',
      name: 'Rapid Fast-Read Digital Thermometer',
      description: '10-second high precision fever alert digital oral and underarm thermometer with LCD screen and beep notification.',
      category: 'First Aid',
      price: 249,
      originalPrice: 350,
      brand: 'ThermoCare',
      image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80',
      stock: 18,
      rating: 4.8,
      reviewsCount: 190,
      specifications: {
        'Response Time': '10-15 seconds',
        'Accuracy': '±0.1°C / ±0.2°F',
        'Battery': 'CR2032 included (Replaceable)',
        'Water Resistant': 'IP22 washable tip',
      },
      usageInfo: 'Press power button, place probe tip firmly under tongue or armpit until long beep sounds. Wipe probe with alcohol swab after use.',
      isEssential: true,
      createdAt: '2026-08-01T11:30:00Z',
    },
    {
      id: 'prod_05',
      name: '75% Isopropyl Alcohol Hand Sanitizer (500 ml)',
      description: 'WHO-recommended formulation with moisturizing aloe vera. Kills 99.9% of germs on contact without stickiness.',
      category: 'Hygiene',
      price: 180,
      originalPrice: 220,
      brand: 'PureProtect',
      image: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=600&q=80',
      stock: 60,
      rating: 4.9,
      reviewsCount: 310,
      specifications: {
        'Volume': '500 ml pump dispenser',
        'Alcohol': '75% Isopropyl Alcohol',
        'Fragrance': 'Mild citrus with Aloe Vera',
      },
      usageInfo: 'Dispense coin-sized amount into palm and rub hands thoroughly over all surfaces for 20 seconds until dry.',
      isEssential: true,
      createdAt: '2026-08-01T12:00:00Z',
    },
    {
      id: 'prod_06',
      name: '3-Ply Disposable Surgical Face Masks (Box of 50)',
      description: 'SITRA tested high-filtration meltblown layer with comfortable elastic earloops and adjustable contour nose clip.',
      category: 'Hygiene',
      price: 199,
      originalPrice: 299,
      brand: 'AirGuard',
      image: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=600&q=80',
      stock: 3, // LOW STOCK ALERT: Only 3 left!
      rating: 4.6,
      reviewsCount: 95,
      specifications: {
        'Quantity': '50 masks per box',
        'Filtration': 'BFE >= 98%',
        'Layers': 'Spunbond + Meltblown + Non-woven inner',
      },
      usageInfo: 'Ensure blue side faces outward. Position wire over bridge of nose, loop around ears, and pinch wire for a sealed fit.',
      isEssential: true,
      createdAt: '2026-08-01T12:30:00Z',
    },
    {
      id: 'prod_07',
      name: 'High Elastic Crepe Bandage (10 cm x 4 m)',
      description: 'Heavy duty elastic compression bandage for sprains, muscle strains, joint support, and sports injury stabilization.',
      category: 'Sports Care',
      price: 140,
      originalPrice: 180,
      brand: 'FlexiWrap',
      image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=600&q=80',
      stock: 40,
      rating: 4.7,
      reviewsCount: 78,
      specifications: {
        'Dimensions': '10 cm width, expands up to 4 meters',
        'Fasteners': '2 metal locking clips included',
        'Washable': 'Reusable and hand washable',
      },
      usageInfo: 'Wrap snugly around the affected ankle or joint, overlapping each turn by half. Do not wrap too tightly to avoid restricting circulation.',
      isEssential: true,
      createdAt: '2026-08-01T13:00:00Z',
    },
    {
      id: 'prod_08',
      name: 'Instant Cold Ice Pack (Chemical Cold Compress - 2 Pcs)',
      description: 'Squeeze-to-activate instant freezing cold pack. Requires no refrigeration. Perfect for acute sports injuries, bumps, and swelling.',
      category: 'Sports Care',
      price: 160,
      originalPrice: 210,
      brand: 'CryoRelief',
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      stock: 22,
      rating: 4.8,
      reviewsCount: 64,
      specifications: {
        'Count': '2 single-use activation packs',
        'Cooling Duration': '20-30 minutes active chill',
        'Activation': 'Firm squeeze & shake',
      },
      usageInfo: 'Locate inner water pouch inside, squeeze firmly until pouch pops, shake to mix contents. Wrap in a light cloth and apply to injury.',
      isEssential: true,
      createdAt: '2026-08-01T13:30:00Z',
    },
    {
      id: 'prod_09',
      name: 'Emergency Thermal Mylar Survival Blanket (Pack of 4)',
      description: 'Space-age military grade aluminized mylar sheet. Reflects up to 90% of body heat to prevent hypothermia during emergency or shock.',
      category: 'Emergency Essentials',
      price: 220,
      originalPrice: 320,
      brand: 'SolarShield',
      image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
      stock: 35,
      rating: 4.9,
      reviewsCount: 142,
      specifications: {
        'Dimensions': '130 cm x 210 cm folded to wallet size',
        'Material': 'Aluminized non-stretch polyester',
        'Protection': 'Windproof, waterproof, heat reflective',
      },
      usageInfo: 'Unfold completely and wrap around torso and extremities with silver side facing inwards toward the body to retain maximum radiant warmth.',
      isEssential: true,
      createdAt: '2026-08-01T14:00:00Z',
    },
    {
      id: 'prod_10',
      name: '120dB Loud Emergency Safety Whistle with Lanyard',
      description: 'High-pitch dual frequency pea-less whistle for disaster survival, campus security, trekking, and emergency alerts.',
      category: 'Emergency Essentials',
      price: 99,
      originalPrice: 150,
      brand: 'SignalSafe',
      image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=600&q=80',
      stock: 4, // LOW STOCK ALERT: Only 4 left!
      rating: 4.7,
      reviewsCount: 52,
      specifications: {
        'Acoustics': '120 decibels (audible up to 1 km)',
        'Design': 'Pea-less, works wet or dry',
        'Attachment': 'Durable reflective neck lanyard',
      },
      usageInfo: 'Blow in bursts of three sharp blasts (standard universal SOS signal) during disorientation or immediate emergency.',
      isEssential: false,
      createdAt: '2026-08-01T14:30:00Z',
    },
    {
      id: 'prod_11',
      name: 'Ultra-Bright Zoomable LED Emergency Flashlight',
      description: '1000 lumen aircraft-grade aluminum flashlight with 5 light modes (High, Med, Low, Strobe, SOS) and USB rechargeable battery.',
      category: 'Emergency Essentials',
      price: 380,
      originalPrice: 550,
      brand: 'LumenBeam',
      image: 'https://images.unsplash.com/photo-1517594422361-5eeb8ae275a9?auto=format&fit=crop&w=600&q=80',
      stock: 19,
      rating: 4.8,
      reviewsCount: 110,
      specifications: {
        'Luminosity': '1000 Lumens XML-T6 LED',
        'Battery': '18650 Li-ion 2200mAh (USB charging cable included)',
        'Water Resistance': 'IPX6 storm-proof',
      },
      usageInfo: 'Cycle through modes with soft clicks on rear tail button. Hold button for 3 seconds to trigger flashing SOS sequence.',
      isEssential: true,
      createdAt: '2026-08-01T15:00:00Z',
    },
    {
      id: 'prod_12',
      name: 'WHO Oral Rehydration Salts (ORS) Electrolyte Sachet (Pack of 10)',
      description: 'Standard clinical formula of essential electrolytes and dextrose to restore fluid balance during heat exhaustion, dehydration, and travel fatigue.',
      category: 'Personal Care',
      price: 95,
      originalPrice: 120,
      brand: 'HydroLife',
      image: 'https://images.unsplash.com/photo-1584365685547-9a5fb6f3a70c?auto=format&fit=crop&w=600&q=80',
      stock: 55,
      rating: 4.9,
      reviewsCount: 230,
      specifications: {
        'Contents': '10 single-dose foil sealed sachets (21.8g each)',
        'Formula': 'WHO Recommended Low Osmolarity ORS',
        'Flavor': 'Orange Electrolyte blend',
      },
      usageInfo: 'Dissolve entire contents of one sachet into exactly 1 liter of fresh, potable drinking water. Consume within 24 hours of mixing.',
      isEssential: true,
      createdAt: '2026-08-01T15:30:00Z',
    },
    {
      id: 'prod_13',
      name: 'DEET-Free Natural Citronella Mosquito & Bug Spray (100 ml)',
      description: 'Herbal protection spray with lemongrass, eucalyptus, and citronella essential oils. Safe for indoor dorms and outdoor monsoon protection.',
      category: 'Monsoon Essentials',
      price: 175,
      originalPrice: 225,
      brand: 'BugGuard Pro',
      image: 'https://images.unsplash.com/photo-1608248597359-bb43eb685b54?auto=format&fit=crop&w=600&q=80',
      stock: 26,
      rating: 4.6,
      reviewsCount: 88,
      specifications: {
        'Volume': '100 ml fine mist spray',
        'Formulation': 'DEET-free, 100% plant-based active botanicals',
        'Duration': 'Up to 6 hours protection per application',
      },
      usageInfo: 'Spray evenly over exposed skin and cuffs of trousers. Avoid spraying directly onto face; apply to hands first then dab cheeks.',
      isEssential: true,
      createdAt: '2026-08-01T16:00:00Z',
    },
    {
      id: 'prod_14',
      name: 'Compact Travel Pill & Essential Organizer Box (7-Day)',
      description: 'Moisture-proof, BPA-free compartment case with silicone sealing ring to keep daily vitamins and emergency essentials organized on the go.',
      category: 'Travel Essentials',
      price: 130,
      originalPrice: 180,
      brand: 'PocketDose',
      image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80',
      stock: 31,
      rating: 4.7,
      reviewsCount: 74,
      specifications: {
        'Compartments': '8 individually latching deep slots',
        'Material': 'Food-grade BPA Free Polypropylene with silicone gasket',
        'Dimensions': '11 x 8 x 3 cm',
      },
      usageInfo: 'Snap lids securely shut until audible click. Store in dry place away from direct sunlight.',
      isEssential: false,
      createdAt: '2026-08-01T16:30:00Z',
    },
    {
      id: 'prod_15',
      name: 'Antiseptic Disinfectant Wound Wipes (Tub of 80)',
      description: 'Benzalkonium chloride alcohol-free soothing antiseptic wipes. Designed for painless cleaning of grazes on delicate or sensitive skin.',
      category: 'First Aid',
      price: 190,
      originalPrice: 240,
      brand: 'MediGuard',
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      stock: 42,
      rating: 4.8,
      reviewsCount: 116,
      specifications: {
        'Count': '80 thick textured non-woven wipes',
        'Alcohol': 'Alcohol-Free, Sting-Free',
        'Packaging': 'Resealable flip-top snap container',
      },
      usageInfo: 'Gently wipe wound area working outwards from center to prevent spreading dirt. Dispose wipe in waste bin.',
      isEssential: true,
      createdAt: '2026-08-01T17:00:00Z',
    },
    {
      id: 'prod_16',
      name: 'Finger Pulse Oximeter with OLED Display',
      description: 'Non-invasive spot check measurement of blood oxygen saturation (%SpO2) and pulse rate with plethysmograph waveform.',
      category: 'Home Essentials',
      price: 599,
      originalPrice: 899,
      brand: 'VitalsTrack',
      image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=600&q=80',
      stock: 14,
      rating: 4.9,
      reviewsCount: 165,
      specifications: {
        'Display': 'Multi-directional 2-color OLED',
        'SpO2 Range': '70% - 99% (Accuracy ±2%)',
        'Power': '2 AAA alkaline batteries included',
      },
      usageInfo: 'Rest hand on flat surface, insert index finger into chamber. Remain still until readings stabilize on screen after 8 seconds.',
      isEssential: false,
      createdAt: '2026-08-01T17:30:00Z',
    },
    {
      id: 'prod_17',
      name: 'Burn Shield Cooling Gel (50 g Tube)',
      description: 'Sterile soothing hydrogel formulated with pure Tea Tree Oil to rapidly dissipate heat from minor burns, scalds, and sunburns.',
      category: 'Home Essentials',
      price: 165,
      originalPrice: 210,
      brand: 'DermaCool',
      image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
      stock: 25,
      rating: 4.8,
      reviewsCount: 89,
      specifications: {
        'Weight': '50 grams sterile tube',
        'Active Cooling': 'Hydrogel base with Melaleuca Alternifolia',
        'Action': 'Immediate heat extraction and pain relief',
      },
      usageInfo: 'Cool burn under running cool tap water for 10 minutes first. Apply generous layer of gel without rubbing. Cover lightly with sterile gauze.',
      isEssential: true,
      createdAt: '2026-08-01T18:00:00Z',
    },
    {
      id: 'prod_18',
      name: 'Stainless Steel Medical Dressing Scissors & Tweezer Set',
      description: 'Surgical stainless steel blunt-tip trauma bandage shears and fine-tip splinter tweezers for safe kit trimming and dressing management.',
      category: 'First Aid',
      price: 185,
      originalPrice: 250,
      brand: 'SurgiSafe',
      image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
      stock: 2, // LOW STOCK ALERT: Only 2 left!
      rating: 4.7,
      reviewsCount: 61,
      specifications: {
        'Items': '1x 14cm Trauma Shears + 1x 10cm Splinter Forceps',
        'Steel': 'Autoclavable 420 Grade Japanese Stainless Steel',
        'Safety': 'Blunt lower shear tip to protect patient skin',
      },
      usageInfo: 'Wipe blades with antiseptic swab before and after each use. Store clean in dry case.',
      isEssential: true,
      createdAt: '2026-08-01T18:30:00Z',
    },
    {
      id: 'prod_19',
      name: 'Microporous Surgical Paper Tape (2.5 cm x 9 m, 2 Rolls)',
      description: 'Gentle, breathable hypoallergenic paper adhesive tape for securing bandages, eye pads, and wound dressings to sensitive skin.',
      category: 'First Aid',
      price: 85,
      originalPrice: 110,
      brand: 'MediGuard',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      stock: 48,
      rating: 4.6,
      reviewsCount: 92,
      specifications: {
        'Quantity': '2 rolls (2.5 cm x 9.1 m each)',
        'Tearability': 'Bi-directional easy hand tearing',
        'Hypoallergenic': 'Latex-free skin-friendly adhesive',
      },
      usageInfo: 'Tear required strip length and press gently over dressing border. Does not leave sticky glue residue on skin.',
      isEssential: true,
      createdAt: '2026-08-01T19:00:00Z',
    },
    {
      id: 'prod_20',
      name: 'Activated Charcoal Water Purification Tablets (Pack of 50)',
      description: 'Emergency potable water purification effervescent tablets for outdoor survival, camping, and monsoon tap water safety.',
      category: 'Monsoon Essentials',
      price: 240,
      originalPrice: 310,
      brand: 'AquaClear',
      image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
      stock: 33,
      rating: 4.8,
      reviewsCount: 104,
      specifications: {
        'Yield': 'Purifies 50 liters (1 tablet per 1 liter)',
        'Standard': 'Meets WHO Drinking Water Guidelines',
        'Shelf Life': '3 years vacuum sealed',
      },
      usageInfo: 'Drop 1 tablet into 1 liter of clear water. Wait 30 minutes before drinking. If water is turbid, pre-filter through cloth first.',
      isEssential: false,
      requiresPrescription: false,
      scheduleType: 'OTC Emergency Essential',
      createdAt: '2026-08-01T19:30:00Z',
    },
    {
      id: 'prod_rx_01',
      name: 'Amoxicillin 500mg Capsules (Strip of 10)',
      description: 'Broad-spectrum antibiotic prescribed for bacterial infections including respiratory tract, ear, and throat conditions. Regulated Schedule H medicine.',
      category: 'Prescription Medicines (Rx)',
      price: 95,
      originalPrice: 120,
      brand: 'Cipla Care',
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      stock: 35,
      rating: 4.8,
      reviewsCount: 72,
      specifications: {
        'Strength': '500 mg per capsule',
        'Form': 'Hard Gelatin Capsules (10 Capsules)',
        'Schedule': 'Schedule H (Prescription Drug)',
        'Storage': 'Store below 25°C in a dry place',
      },
      usageInfo: 'Strictly as prescribed by your registered medical practitioner. Complete the full course even if symptoms subside.',
      isEssential: false,
      requiresPrescription: true,
      dosageForm: 'Capsules (Strip of 10)',
      scheduleType: 'Schedule H (Prescription Required)',
      createdAt: '2026-08-05T10:00:00Z',
    },
    {
      id: 'prod_rx_02',
      name: 'Salbutamol Inhaler 100mcg (200 Metered Doses)',
      description: 'Bronchodilator aerosol inhaler providing rapid relief from asthma symptoms, bronchospasm, and shortness of breath.',
      category: 'Prescription Medicines (Rx)',
      price: 175,
      originalPrice: 210,
      brand: 'Asthavent Care',
      image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80',
      stock: 22,
      rating: 4.9,
      reviewsCount: 94,
      specifications: {
        'Dose': '100 mcg per actuation',
        'Canister Capacity': '200 metered actuations',
        'Schedule': 'Schedule H (Prescription Drug)',
        'Type': 'CFC-free Metered Dose Inhaler',
      },
      usageInfo: 'Inhale through mouth as directed by physician. Shake well before each use. Rinse mouth with water after inhalation.',
      isEssential: true,
      requiresPrescription: true,
      dosageForm: 'Pressurized Inhaler (200 Doses)',
      scheduleType: 'Schedule H (Prescription Required)',
      createdAt: '2026-08-05T11:00:00Z',
    },
    {
      id: 'prod_rx_03',
      name: 'Metformin 500mg Prolonged Release Tablets (Strip of 15)',
      description: 'First-line medication for the treatment of type 2 diabetes mellitus to manage blood glucose levels.',
      category: 'Prescription Medicines (Rx)',
      price: 48,
      originalPrice: 65,
      brand: 'GlyciMet Pharma',
      image: 'https://images.unsplash.com/photo-1550572017-ed200f5e6343?auto=format&fit=crop&w=600&q=80',
      stock: 50,
      rating: 4.7,
      reviewsCount: 110,
      specifications: {
        'Strength': '500 mg Prolonged-Release',
        'Quantity': '15 Tablets in blister pack',
        'Schedule': 'Schedule H (Prescription Drug)',
      },
      usageInfo: 'Take with or immediately after meals to reduce gastrointestinal side effects. Swallow whole; do not crush.',
      isEssential: false,
      requiresPrescription: true,
      dosageForm: 'Tablets (Strip of 15)',
      scheduleType: 'Schedule H (Prescription Required)',
      createdAt: '2026-08-05T11:30:00Z',
    },
    {
      id: 'prod_rx_04',
      name: 'Atorvastatin 20mg Lipid Lowering Tablets (Strip of 10)',
      description: 'Statin medication prescribed to lower LDL cholesterol and triglycerides in blood, reducing cardiovascular risks.',
      category: 'Prescription Medicines (Rx)',
      price: 120,
      originalPrice: 155,
      brand: 'LipidSafe Care',
      image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80',
      stock: 40,
      rating: 4.8,
      reviewsCount: 88,
      specifications: {
        'Strength': '20 mg per film-coated tablet',
        'Packaging': '10 Tablets in Alu-Alu strip',
        'Schedule': 'Schedule H (Prescription Drug)',
      },
      usageInfo: 'Usually taken once daily at bedtime with or without food. Avoid grapefruit consumption during treatment.',
      isEssential: false,
      requiresPrescription: true,
      dosageForm: 'Tablets (Strip of 10)',
      scheduleType: 'Schedule H (Prescription Required)',
      createdAt: '2026-08-05T12:00:00Z',
    },
    {
      id: 'prod_rx_05',
      name: 'Azithromycin 500mg Tablets (Strip of 3)',
      description: 'Macrolide antibiotic used to treat bacterial chest infections, throat infections, and sinusitis. Short 3-day treatment.',
      category: 'Prescription Medicines (Rx)',
      price: 85,
      originalPrice: 110,
      brand: 'AzithroMed Labs',
      image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
      stock: 18,
      rating: 4.9,
      reviewsCount: 65,
      specifications: {
        'Strength': '500 mg per tablet',
        'Quantity': '3 film-coated tablets',
        'Schedule': 'Schedule H1 (High Alert Prescription Drug)',
      },
      usageInfo: 'Take once daily 1 hour before or 2 hours after meals for 3 consecutive days as advised by your physician.',
      isEssential: false,
      requiresPrescription: true,
      dosageForm: 'Tablets (Strip of 3)',
      scheduleType: 'Schedule H1 (Prescription Required)',
      createdAt: '2026-08-05T12:30:00Z',
    },
    {
      id: 'prod_rx_06',
      name: 'Pantoprazole Gastro-Resistant 40mg Tablets (Strip of 15)',
      description: 'Proton pump inhibitor (PPI) that decreases stomach acid secretion for GERD, acid reflux, and peptic ulcers.',
      category: 'Prescription Medicines (Rx)',
      price: 110,
      originalPrice: 145,
      brand: 'PanPro Health',
      image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80',
      stock: 30,
      rating: 4.8,
      reviewsCount: 104,
      specifications: {
        'Strength': '40 mg enteric-coated',
        'Packaging': '15 Tablets strip',
        'Schedule': 'Schedule H (Prescription Drug)',
      },
      usageInfo: 'Take 1 tablet once daily in the morning 30 minutes before breakfast with a glass of water.',
      isEssential: true,
      requiresPrescription: true,
      dosageForm: 'Tablets (Strip of 15)',
      scheduleType: 'Schedule H (Prescription Required)',
      createdAt: '2026-08-05T13:00:00Z',
    },
  ],
  kits: [
    {
      id: 'kit_college_01',
      name: 'College Emergency Kit',
      description: 'Designed specifically for students living in dorms, PGs, and campus hostels. Compact, compliant, and covers daily scrapes, late-night study emergencies, and basic hygiene.',
      category: 'College Essentials',
      situation: 'College',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_01', quantity: 1 }, // Bandages (₹149)
        { productId: 'prod_02', quantity: 1 }, // Cotton Gauze (₹120)
        { productId: 'prod_03', quantity: 1 }, // Antiseptic Solution (₹110)
        { productId: 'prod_04', quantity: 1 }, // Thermometer (₹249)
        { productId: 'prod_05', quantity: 1 }, // Sanitizer (₹180)
        { productId: 'prod_06', quantity: 1 }, // Face Masks (₹199)
      ],
      // Total individual: 149 + 120 + 110 + 249 + 180 + 199 = 1007
      normalPrice: 1007,
      bundlePrice: 849,
      savings: 158,
      isPopular: true,
      createdAt: '2026-08-05T10:00:00Z',
    },
    {
      id: 'kit_travel_02',
      name: 'Travel Safety Kit',
      description: 'Compact flight and road-trip certified emergency kit with motion sickness remedies, hygiene supplies, electrolyte replenishment, and pocket organizer.',
      category: 'Travel Essentials',
      situation: 'Travel',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_01', quantity: 1 }, // Bandages (149)
        { productId: 'prod_05', quantity: 1 }, // Sanitizer (180)
        { productId: 'prod_12', quantity: 2 }, // ORS Salts (95 x 2 = 190)
        { productId: 'prod_14', quantity: 1 }, // Travel Pill Box (130)
        { productId: 'prod_09', quantity: 1 }, // Thermal Survival Blanket (220)
      ],
      // Normal: 149 + 180 + 190 + 130 + 220 = 869
      normalPrice: 869,
      bundlePrice: 720,
      savings: 149,
      isPopular: true,
      createdAt: '2026-08-05T10:30:00Z',
    },
    {
      id: 'kit_sports_03',
      name: 'Sports First-Aid Kit',
      description: 'Tailored for athletes, runners, gym enthusiasts, and sports teams. Rapid stabilization for sprains, muscle strains, cuts, and acute impact swelling.',
      category: 'Sports Care',
      situation: 'Sports',
      image: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_07', quantity: 2 }, // Crepe Bandage (140 x 2 = 280)
        { productId: 'prod_08', quantity: 2 }, // Instant Cold Pack (160 x 2 = 320)
        { productId: 'prod_01', quantity: 1 }, // Bandages (149)
        { productId: 'prod_15', quantity: 1 }, // Antiseptic Wipes (190)
        { productId: 'prod_12', quantity: 1 }, // ORS Electrolytes (95)
      ],
      // Normal: 280 + 320 + 149 + 190 + 95 = 1034
      normalPrice: 1034,
      bundlePrice: 875,
      savings: 159,
      isPopular: false,
      createdAt: '2026-08-05T11:00:00Z',
    },
    {
      id: 'kit_home_04',
      name: 'Home First-Aid Kit',
      description: 'Comprehensive family healthcare and emergency station. Preparedness for kitchen burns, accidental cuts, children fever monitoring, and oxygen check.',
      category: 'Home Essentials',
      situation: 'Home',
      image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_01', quantity: 1 }, // Bandages (149)
        { productId: 'prod_03', quantity: 1 }, // Antiseptic Solution (110)
        { productId: 'prod_04', quantity: 1 }, // Thermometer (249)
        { productId: 'prod_17', quantity: 1 }, // Burn Gel (165)
        { productId: 'prod_18', quantity: 1 }, // Scissors & Tweezer Set (185)
        { productId: 'prod_19', quantity: 1 }, // Paper Tape (85)
        { productId: 'prod_16', quantity: 1 }, // Pulse Oximeter (599)
      ],
      // Normal: 149 + 110 + 249 + 165 + 185 + 85 + 599 = 1542
      normalPrice: 1542,
      bundlePrice: 1299,
      savings: 243,
      isPopular: true,
      createdAt: '2026-08-05T11:30:00Z',
    },
    {
      id: 'kit_office_05',
      name: 'Office Emergency Kit',
      description: 'Corporate workplace safety kit meeting workplace safety standards. Easily accessible for department floors, desks, and meeting rooms.',
      category: 'Emergency Essentials',
      situation: 'Office',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_01', quantity: 2 }, // Bandages (149 x 2 = 298)
        { productId: 'prod_05', quantity: 2 }, // Sanitizer 500ml (180 x 2 = 360)
        { productId: 'prod_06', quantity: 1 }, // 50 Masks (199)
        { productId: 'prod_04', quantity: 1 }, // Thermometer (249)
        { productId: 'prod_15', quantity: 1 }, // Antiseptic Wipes (190)
        { productId: 'prod_11', quantity: 1 }, // Emergency Flashlight (380)
      ],
      // Normal: 298 + 360 + 199 + 249 + 190 + 380 = 1676
      normalPrice: 1676,
      bundlePrice: 1399,
      savings: 277,
      isPopular: false,
      createdAt: '2026-08-05T12:00:00Z',
    },
    {
      id: 'kit_monsoon_06',
      name: 'Monsoon Preparedness Kit',
      description: 'Essential seasonal defense against waterborne illnesses, water purification, mosquitoes, storm power cuts, and fungal foot protection.',
      category: 'Monsoon Essentials',
      situation: 'Monsoon',
      image: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_13', quantity: 1 }, // Mosquito Spray (175)
        { productId: 'prod_20', quantity: 1 }, // Water Purification (240)
        { productId: 'prod_11', quantity: 1 }, // Emergency Flashlight (380)
        { productId: 'prod_01', quantity: 1 }, // Waterproof Bandages (149)
        { productId: 'prod_05', quantity: 1 }, // Sanitizer (180)
      ],
      // Normal: 175 + 240 + 380 + 149 + 180 = 1124
      normalPrice: 1124,
      bundlePrice: 940,
      savings: 184,
      isPopular: true,
      createdAt: '2026-08-05T12:30:00Z',
    },
    {
      id: 'kit_hostel_07',
      name: 'Hostel Hygiene Kit',
      description: 'Curated specifically for students in shared dorm bathrooms. Focused on personal hygiene, antibacterial defense, and quick sanitization.',
      category: 'Hygiene',
      situation: 'Hostel',
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_05', quantity: 1 }, // Sanitizer (180)
        { productId: 'prod_15', quantity: 1 }, // Antiseptic Wipes (190)
        { productId: 'prod_06', quantity: 1 }, // Masks (199)
        { productId: 'prod_01', quantity: 1 }, // Bandages (149)
        { productId: 'prod_12', quantity: 1 }, // ORS Sachets (95)
      ],
      // Normal: 180 + 190 + 199 + 149 + 95 = 813
      normalPrice: 813,
      bundlePrice: 690,
      savings: 123,
      isPopular: false,
      createdAt: '2026-08-05T13:00:00Z',
    },
    {
      id: 'kit_outdoor_08',
      name: 'Outdoor Activities Survival Kit',
      description: 'Built for hikers, campers, trekkers, and adventurers. Rugged emergency gear, whistle, thermal protection, wound care, and flashlight.',
      category: 'Emergency Essentials',
      situation: 'Outdoor Activities',
      image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
      items: [
        { productId: 'prod_09', quantity: 2 }, // Thermal Blanket (220 x 2 = 440)
        { productId: 'prod_10', quantity: 1 }, // Emergency Whistle (99)
        { productId: 'prod_11', quantity: 1 }, // LED Flashlight (380)
        { productId: 'prod_07', quantity: 1 }, // Crepe Bandage (140)
        { productId: 'prod_01', quantity: 1 }, // Waterproof Bandages (149)
        { productId: 'prod_20', quantity: 1 }, // Water Purification (240)
      ],
      // Normal: 440 + 99 + 380 + 140 + 149 + 240 = 1448
      normalPrice: 1448,
      bundlePrice: 1199,
      savings: 249,
      isPopular: true,
      createdAt: '2026-08-05T13:30:00Z',
    },
  ],
  cart: [],
  orders: [
    {
      id: 'MB-10928',
      userId: 'usr_demo_01',
      customerName: 'Aarav Sharma',
      customerEmail: 'user@medibasket.com',
      customerPhone: '+91 98765 43210',
      items: [
        {
          kitId: 'kit_college_01',
          name: 'College Emergency Kit',
          price: 849,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
          isKit: true,
          kitItemsSummary: 'Bandages, Gauze Swabs, Antiseptic Solution, Thermometer, Sanitizer, Masks',
        },
      ],
      kitId: 'kit_college_01',
      kitName: 'College Emergency Kit',
      subtotal: 849,
      discount: 50,
      deliveryFee: 0,
      totalAmount: 799,
      address: {
        fullName: 'Aarav Sharma',
        phone: '+91 98765 43210',
        email: 'user@medibasket.com',
        streetAddress: 'Flat 402, Green Glen Residency, Bellandur',
        city: 'Bengaluru',
        pincode: '560103',
      },
      paymentMethod: 'online_simulated',
      status: 'Delivered',
      trackingHistory: [
        {
          status: 'Order Placed',
          timestamp: '2026-09-12T09:15:00Z',
          description: 'Order confirmed and verified via instant simulated gateway.',
          location: 'MediBasket Hub, Bengaluru',
        },
        {
          status: 'Packed',
          timestamp: '2026-09-12T14:30:00Z',
          description: 'Emergency kit items sterilized, securely sealed and boxed with batch certificates.',
          location: 'Fulfillment Center 2, Bengaluru',
        },
        {
          status: 'Shipped',
          timestamp: '2026-09-13T08:00:00Z',
          description: 'Package dispatched via Express Health Courier (Tracking #EHC-88219).',
          location: 'Hub Transit Center, Bengaluru',
        },
        {
          status: 'Out for Delivery',
          timestamp: '2026-09-14T09:30:00Z',
          description: 'Delivery associate Manoj K. is en route to Bellandur location.',
          location: 'Bellandur Local Sorting Depot',
        },
        {
          status: 'Delivered',
          timestamp: '2026-09-14T12:45:00Z',
          description: 'Package handed directly to customer Aarav Sharma.',
          location: 'Flat 402, Green Glen Residency',
        },
      ],
      createdAt: '2026-09-12T09:15:00Z',
      deliveredAt: '2026-09-14T12:45:00Z',
    },
    {
      id: 'MB-10984',
      userId: 'usr_demo_01',
      customerName: 'Aarav Sharma',
      customerEmail: 'user@medibasket.com',
      customerPhone: '+91 98765 43210',
      items: [
        {
          kitId: 'kit_travel_02',
          name: 'Travel Safety Kit',
          price: 720,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
          isKit: true,
          kitItemsSummary: 'Bandages, Sanitizer, ORS Salts (x2), Travel Pill Box, Thermal Blanket',
        },
        {
          productId: 'prod_11',
          name: 'Ultra-Bright Zoomable LED Emergency Flashlight',
          price: 380,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1517594422361-5eeb8ae275a9?auto=format&fit=crop&w=600&q=80',
          isKit: false,
        },
      ],
      subtotal: 1100,
      discount: 100,
      deliveryFee: 0,
      totalAmount: 1000,
      address: {
        fullName: 'Aarav Sharma',
        phone: '+91 98765 43210',
        email: 'user@medibasket.com',
        streetAddress: 'Flat 402, Green Glen Residency, Bellandur',
        city: 'Bengaluru',
        pincode: '560103',
      },
      paymentMethod: 'cod',
      status: 'Shipped',
      trackingHistory: [
        {
          status: 'Order Placed',
          timestamp: '2026-09-16T11:00:00Z',
          description: 'Order confirmed with Cash on Delivery.',
          location: 'MediBasket Hub, Bengaluru',
        },
        {
          status: 'Packed',
          timestamp: '2026-09-16T17:20:00Z',
          description: 'Items packed in weather-resistant safety packaging.',
          location: 'Fulfillment Center 1, Bengaluru',
        },
        {
          status: 'Shipped',
          timestamp: '2026-09-17T08:15:00Z',
          description: 'Dispatched on courier vehicle. In transit to local hub.',
          location: 'Regional Logistics Center',
        },
      ],
      createdAt: '2026-09-16T11:00:00Z',
    },
  ],
  savedKits: [
    {
      id: 'saved_kit_01',
      userId: 'usr_demo_01',
      name: 'My Custom Exam Study First-Aid Kit',
      purpose: 'College',
      items: [
        { productId: 'prod_01', quantity: 1 },
        { productId: 'prod_04', quantity: 1 },
        { productId: 'prod_12', quantity: 2 },
        { productId: 'prod_05', quantity: 1 },
      ],
      normalPrice: 673,
      bundlePrice: 580,
      savings: 93,
      createdAt: '2026-09-10T14:00:00Z',
      updatedAt: '2026-09-10T14:00:00Z',
    },
  ],
  wishlist: [
    {
      id: 'wish_01',
      userId: 'usr_demo_01',
      productId: 'prod_16', // Pulse Oximeter
      createdAt: '2026-09-08T12:00:00Z',
    },
    {
      id: 'wish_02',
      userId: 'usr_demo_01',
      productId: 'prod_11', // Emergency Flashlight
      createdAt: '2026-09-09T15:00:00Z',
    },
  ],
  reviews: [
    {
      id: 'rev_01',
      productId: 'prod_01',
      userId: 'usr_demo_01',
      userName: 'Aarav Sharma',
      orderId: 'MB-10928',
      rating: 5,
      comment: 'Super fast delivery for our college dorm. The sterile bandages stayed completely waterproof during handwashing.',
      createdAt: '2026-09-15T10:00:00Z',
    },
    {
      id: 'rev_02',
      productId: 'prod_04',
      userId: 'usr_demo_01',
      userName: 'Aarav Sharma',
      orderId: 'MB-10928',
      rating: 5,
      comment: 'The 10-second thermometer is super accurate and easy to read. Highly recommended for any student kit.',
      createdAt: '2026-09-15T10:30:00Z',
    },
  ],
  prescriptions: [
    {
      id: 'rx_01',
      userId: 'usr_demo_01',
      userName: 'Aarav Sharma',
      userEmail: 'user@medibasket.com',
      userPhone: '+91 98765 43210',
      patientName: 'Aarav Sharma',
      doctorName: 'Dr. Neha Mehra (MD, Reg #MED-77412)',
      hospitalOrClinic: 'Apollo Health City Clinic, Bengaluru',
      prescriptionDate: '2026-09-14',
      fileUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
      fileName: 'Doctor_Prescription_DrNeha_Aarav.pdf',
      fileSize: '1.2 MB',
      notes: 'Prescribed for acute respiratory infection: Amoxicillin 500mg (1 tid x 5 days) + Salbutamol Inhaler as needed.',
      status: 'approved',
      verifiedBy: 'Chief Pharmacist R. Verma (Reg #PH-99201)',
      verifiedAt: '2026-09-15T10:30:00Z',
      uploadedAt: '2026-09-15T09:15:00Z',
    },
    {
      id: 'rx_02',
      userId: 'usr_demo_01',
      userName: 'Aarav Sharma',
      userEmail: 'user@medibasket.com',
      userPhone: '+91 98765 43210',
      patientName: 'Ramesh Sharma (Father)',
      doctorName: 'Dr. Suresh Rao (Cardiologist, Reg #KAR-44219)',
      hospitalOrClinic: 'Fortis Cardiac Institute, Bengaluru',
      prescriptionDate: '2026-09-16',
      fileUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
      fileName: 'Rx_Cardio_Atorvastatin_Metformin.jpg',
      fileSize: '850 KB',
      notes: 'Long term therapy: Atorvastatin 20mg tab OD at bedtime, Metformin 500mg tab BD after meals.',
      status: 'pending',
      uploadedAt: '2026-09-17T18:40:00Z',
    },
    {
      id: 'rx_03',
      userId: 'usr_demo_02',
      userName: 'Pooja Nair',
      userEmail: 'pooja@example.com',
      userPhone: '+91 97111 22334',
      patientName: 'Pooja Nair',
      doctorName: 'Dr. K. Swaminathan (Reg #TN-10294)',
      hospitalOrClinic: 'City Health Diagnostic Center',
      prescriptionDate: '2026-03-01',
      fileUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
      fileName: 'Old_Prescription_Scan.png',
      fileSize: '420 KB',
      notes: 'Sample expired prescription',
      status: 'rejected',
      rejectionReason: 'Prescription date is older than 6 months. Under Indian Pharmacy Regulations, an active prescription issued within 90 days is required.',
      verifiedBy: 'Pharmacist R. Verma',
      verifiedAt: '2026-09-16T12:00:00Z',
      uploadedAt: '2026-09-16T11:20:00Z',
    },
  ],
};
